<?php namespace ProcessWire;

/**
 * ProcessWire 'SubscribeToConstantContactKeepAlive' module (uses LazyCron)
 * 
 * ProcessWire 3.x, Copyright by Ryan Cramer
 * https://processwire.com
 *
 */

class SubscribeToConstantContactKeepAlive extends WireData implements Module {

	/**
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Subscribe to Constant Contact Keep Alive - LazyCron Adapter',
			'version' => "0.0.1",
			'summary' => 'A module to keep the ConstantContact module\'s API credentials valid.',
			'singular' => true,
			'autoload' => true,
			'icon' => 'address-card',
            'requires' => [
				'LazyCron',
				'SubscribeToConstantContact'
			]
        );
	}

	public function init() {
        $myModule = $this->modules->get("SubscribeToConstantContact");
        $this->addHook('LazyCron::everyDay', $myModule, 'checkTokenCron');
	}
}
